# Modules
- color: "fbca04"
  description: "This issue or pull request is related to kms-key module."
  name: ":floppy_disk: kms-key"
- color: "fbca04"
  description: "This issue or pull request is related to kms-replica-key module."
  name: ":floppy_disk: kms-replica-key"
- color: "fbca04"
  description: "This issue or pull request is related to secrets-manager-secret module."
  name: ":floppy_disk: secrets-manager-secret"
- color: "fbca04"
  description: "This issue or pull request is related to ssm-parameter-store-parameter module."
  name: ":floppy_disk: ssm-parameter-store-parameter"
- color: "fbca04"
  description: "This issue or pull request is related to ssm-parameter-store-parameter-set module."
  name: ":floppy_disk: ssm-parameter-store-parameter-set"
- color: "fbca04"
  description: "This issue or pull request is related to ssm-parameter-store-settings module."
  name: ":floppy_disk: ssm-parameter-store-settings"
